module GrayCodePosition

import Base: eltype, length, diff, iterate

export GrayCode, GrayCodePositions

"""
    GrayCode(n::Integer)
Represents the [Gray code](https://en.wikipedia.org/wiki/Gray_code) over `n` bits. `n` must be positive. 
GrayCode implements iteration to generate all codewords.
"""
struct GrayCode
    nbits::Int64
    function GrayCode(n::Integer)
        n <= 0 && Base.throw(ArgumentError("Code must have positive length!")) 
        new(n)
    end
end
eltype(::GrayCode) = Int64
diff(code::GrayCode) = GrayCodePositions(code)
length(code::GrayCode) = (1 << code.nbits)
iterate(code::GrayCode) = (0,1)
function iterate(code::GrayCode, state)  
 state == length(code) && return nothing
 (state ⊻ (state >> 1),state + 1)
end

"""
    GrayCodePositions(code::GrayCode)

Represents the sequence of transient indices of a Gray code. 
The `i`th transient index is the position of the bit of `code[i]` that is flipped to obtain `code[i+1]`.
The entire sequence can be generated by iteration.
**Note:** The returned transient indices are `1`-based.  
"""
struct GrayCodePositions
    code::GrayCode
end
const GCP = GrayCodePositions;


eltype(::GCP) = Int64; 
# Note the varying positions are one less than the total number of codes
length(gcp::GCP) = length(gcp.code) - 1
iterate(gcp::GCP) =  (one(eltype(gcp)), 1)

function Base.iterate(gcp::GCP, state) 
    state == length(gcp) && return nothing
    n = state + 1;
    (trailing_zeros(n) + 1, n)
end 

end
